options:
    title: [Enter your server name]
command /marry <player>:
    permission: marriage.marry.use
    permission message: &4Sorry, you can't use this without permission.
    trigger:
        if player is not {married.%player%}:
            set {marriage.request.%player%} to player
            set {marriage.requested.%player%} to arg 1
        else if player is {married.%player%}:
            cancel event
            send "{@title} >> &4Sorry, you can't use this command."